2025-05-15 13:04:28,490 INFO    MainThread:2097331 [wandb_setup.py:_flush():76] Current SDK version is 0.15.2
2025-05-15 13:04:28,490 INFO    MainThread:2097331 [wandb_setup.py:_flush():76] Configure stats pid to 2097331
2025-05-15 13:04:28,490 INFO    MainThread:2097331 [wandb_setup.py:_flush():76] Loading settings from /global/homes/k/katiekee/.config/wandb/settings
2025-05-15 13:04:28,490 INFO    MainThread:2097331 [wandb_setup.py:_flush():76] Loading settings from /pscratch/sd/k/katiekee/PDFParameterInference/wandb/settings
2025-05-15 13:04:28,490 INFO    MainThread:2097331 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2025-05-15 13:04:28,490 INFO    MainThread:2097331 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-05-15 13:04:28,490 INFO    MainThread:2097331 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'cl.py', 'program': '/pscratch/sd/k/katiekee/PDFParameterInference/cl.py'}
2025-05-15 13:04:28,491 INFO    MainThread:2097331 [wandb_init.py:_log_setup():507] Logging user logs to /pscratch/sd/k/katiekee/PDFParameterInference/wandb/run-20250515_130428-ip8s8gdh/logs/debug.log
2025-05-15 13:04:28,491 INFO    MainThread:2097331 [wandb_init.py:_log_setup():508] Logging internal logs to /pscratch/sd/k/katiekee/PDFParameterInference/wandb/run-20250515_130428-ip8s8gdh/logs/debug-internal.log
2025-05-15 13:04:28,491 INFO    MainThread:2097331 [wandb_init.py:init():547] calling init triggers
2025-05-15 13:04:28,491 INFO    MainThread:2097331 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'num_samples': 10000, 'num_events': 1000000, 'num_epochs': 20, 'batch_size': 4, 'lr': 0.001}
2025-05-15 13:04:28,491 INFO    MainThread:2097331 [wandb_init.py:init():596] starting backend
2025-05-15 13:04:28,491 INFO    MainThread:2097331 [wandb_init.py:init():600] setting up manager
2025-05-15 13:04:28,493 INFO    MainThread:2097331 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-15 13:04:28,497 INFO    MainThread:2097331 [wandb_init.py:init():606] backend started and connected
2025-05-15 13:04:28,499 INFO    MainThread:2097331 [wandb_init.py:init():700] updated telemetry
2025-05-15 13:04:28,528 INFO    MainThread:2097331 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2025-05-15 13:04:29,169 INFO    MainThread:2097331 [wandb_run.py:_on_init():2177] communicating current version
2025-05-15 13:04:29,272 INFO    MainThread:2097331 [wandb_run.py:_on_init():2186] got version response upgrade_message: "wandb version 0.19.11 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-05-15 13:04:29,273 INFO    MainThread:2097331 [wandb_init.py:init():787] starting run threads in backend
2025-05-15 13:04:30,021 WARNING MainThread:2097331 [wandb_init.py:init():1172] interrupted
Traceback (most recent call last):
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1150, in init
    run = wi.init()
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 799, in init
    run_start_result = run_start_handle.wait(timeout=30)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 283, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 130, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _wait
    return self._event.wait(timeout=timeout)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/global/common/software/nersc9/pytorch/2.0.1/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2025-05-15 13:04:37,235 WARNING MsgRouterThr:2097331 [router.py:message_loop():77] message_loop has been closed
